services:
  azurefunction21:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - connection-azure-function=Server=azurefunction.mysql;Port=3306;Database=pocazurefunction;User=mysqluser;Password=root;SslMode=None
      - IsEncrypted=false
      # - AzureWebJobsStorage=UseDevelopmentStorage=true # conflicting with Timer
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - WEBSITE_SITE_NAME=MyAzureFunctionApp
      - AzureWebJobsScriptRoot=/home/site/wwwroot
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
    ports:
      - "8085:8080"
    networks:
      - azurefunction-network
    depends_on:
      - azurefunction.adminer

  # MYSQL
  azurefunction.mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "pocazurefunction"
      MYSQL_USER: "mysqluser"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "3316:3306"
    volumes:
      - ../mysql-script/volume-mysql:/var/lib/mysql
      - ../mysql-script/initial_script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - azurefunction-network

  # ADMINER
  azurefunction.adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - azurefunction-network
    depends_on:
      - azurefunction.mysql
   
    # Admire Auth
    # Server: "azurefunction.mysql"
    # Username: "mysqluser"
    # Password: "root"
    # Database: "pocazurefunction"

networks:
  azurefunction-network:
    driver: bridge

volumes:
  sql_data:
    driver: local