CREATE DATABASE IF NOT EXISTS pocazurefunction;

USE pocazurefunction;

DROP TABLE IF EXISTS customer;

CREATE TABLE `customer` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `az_func_updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `IsDeleted` TINYINT(1) DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Email` (`Email`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

GRANT PROCESS ON pocazurefunction.* TO 'mysqluser'@'%';
FLUSH PRIVILEGES;
